
name: update cmor tables
on:
  push:
    #    paths:
    ##  - 'cmor-table/datasets.csv'
    branches:
      - '*'
  workflow_dispatch:

jobs:
  update_cmor_tables:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout data request
      uses: actions/checkout@v4

    - name: checkout cordex cmor tables
      uses: actions/checkout@v4
      with:
        repository: WCRP-CORDEX/cordex-cmip6-cmor-tables
        path: tables
        token: ${{ secrets.TABLE_ACCESS_TOKEN }}

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./ci/requirements.txt

    - name: Create tables
      run: |
        create-cmor-tables https://raw.githubusercontent.com/WCRP-CORDEX/data-request-table/refs/heads/main/cmor-table/datasets.csv --coords --output tables/Tables
